CREATE DATABASE IF NOT EXISTS locationsofi_db;
USE locationsofi_db;

CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS devices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hwid VARCHAR(100) UNIQUE NOT NULL,
    user_tag VARCHAR(100) DEFAULT 'New User',
    status VARCHAR(20) DEFAULT 'PENDING',
    expiry_date DATETIME NULL,
    remote_lat DOUBLE NULL,
    remote_lng DOUBLE NULL,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
